### ISSUE TITLE
Update doesn't maintain semver constraint

### ISSUE THREAD

**Issue by felixfbecker** [dependencies-io/actor-php-composer#7]
This PR was opened by dependencies.io:
```diff
From 10d94e01140a3aa7dae63642608ba3b3554cafc3 Mon Sep 17 00:00:00 2001
From: "Dependencies.io Bot" <bot@dependencies.io>
Date: Sun, 22 Oct 2017 20:48:56 +0000
Subject: [PATCH]  phpdocumentor/reflection-docblock from 3.3.0 to 4.0.0

---
 composer.json | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/composer.json b/composer.json
index 4a1c393..064f956 100644
--- a/composer.json
+++ b/composer.json
@@ -22,7 +22,7 @@
     "require": {
         "php": ">=7.0",
         "netresearch/jsonmapper": "^1.0",
-        "phpdocumentor/reflection-docblock": "^3.1"
+        "phpdocumentor/reflection-docblock": "4.0.0"
     },
     "require-dev": {
         "phpunit/phpunit": "^5.5"
```
Note how before, it was a semver range `^3.1` giving all minor or patch releases within v3, while the PR changes it to be locked at `4.0.0`

**Comment by davegaeddert** [comment]
Yeah, that's definitely the case. 

I think all that needs to happen is to parse the constraints that they were using and try to copy them forward in the `composer require` commands.

https://github.com/dependencies-io/actor-php-composer/blob/284cad975a85b6c3b15d0d7efdd0e4a2dd258de5/entrypoint.php#L51-L54

Off the top of my head, feels like we will be able to copy `~` and `^` over, but anything else is too complex and we will probably just have to drop it?
https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators

Not sure that I personally will be able to get to this right away, more than happy to look at a PR though.

**Comment by felixfbecker** [comment]
Yeah personally I'd be fine with only supporting `^`, `~` and locked versions.
Should the actor parse these out? Or the collector?

**Comment by davegaeddert** [comment]
Actor. I would just say that right before it uses the `compose require` commands, it should take a look at the composer.json and try to figure out what pattern (`^` or `~`) the user is using -- might be as simple as checking what the first character in the constraint is...but there will probably things like `||` that make that not 100% reliable.

**Comment by davegaeddert** [comment]
Follow-up thought on this... At the same time, it should see whether the new version fits within whatever they had specified. If it does, then we don't need to update composer.json at all. If it doesn't then we can update it as an "out of range update" and try to keep the same prefix that they were using.

**Comment by felixfbecker** [comment]
👍

**Comment by davegaeddert** [comment]
Would also be a good time to work in the `dev-` changes that we made on the collector to smooth out that flow. i.e. if we're updating to the latest commit of `dev-master`, then we just need to update the lockfile following the same logic.

**Comment by davegaeddert** [comment]
Took a stab in #15
