### ISSUE TITLE
Actor fails if there is a version conflict

### ISSUE THREAD

**Issue by felixfbecker** [dependencies-io/actor-php-composer#8]
Since Composer uses a flat dependency tree (because PHP namespaces are global and there is no "module resolution" like in Node) you can only have one version of a package installed at a time. This quite often causes a conflict if you just `composer require` a new major version but some other dependency depends on the old version (usually solved by also updating that dependency). Atm this makes the whole actor fail, therefor no PR is opened. I think it would be a better user experience if the require error was ignored and the PR with the updated composer.json opened, let CI fail and a human take care of it.

**Comment by davegaeddert** [comment]
A lot of the thinking around how updates are made has changed in dependencies.io v2. The php repo is here: https://github.com/dependencies-io/php

In general, lockfile vs manifest updates are two separate concepts now, so I suspect this is less of a problem now. I'd encourage you to check out the new stuff if you haven't yet!
